version: "3"
services:
  turtlebot3_kinetic:
    container_name: kinetic-tb3
    image: kinetic:tb3
    privileged: true
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - DISPLAY=${DISPLAY}
#       - PULSE_SERVER=unix:/tmp/pulseaudio.socket
#       - PULSE_COOKIE=/tmp/pulseaudio.cookie
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
         #source: ~/catkin_ws/src/turtlebot3_common
       - /dev:/dev
#       - /home/asakayusuke/turtlebot_kinetic_docker/turtlebot3_common:/home/${USER_NAME}/catkin_ws/src/turtlebot3_common
#        - /home/asakayusuke/turtlebot_kinetic_docker/tb3_common:/home/${USER_NAME}/catkin_ws/src/tb3_common
#        - /home/asakayusuke/turtlebot_kinetic_docker/tb3_navigation:/home/${USER_NAME}/catkin_ws/src/tb3_navigation

    devices:
       - /dev:/dev
    ipc: "host"
    network_mode: host
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    command: /bin/bash
