services:
  turtlebot3_noetic:
    container_name: noetic-tb3
    image: noetic:tb3
    privileged: true
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority/:/root/.Xauthority
       - /dev:/dev
       - /home/asakayusuke/turtlebot_noetic_docker/tb3_common:/home/${USER_NAME}/catkin_ws/src/tb3_common
    devices:
       - /dev:/dev
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"
    command: /bin/bash
